# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  # Auto-detect host based on hostname or allow override
  DETECTED_HOST:
    sh: |
      hostname=$(hostname)
      case "$hostname" in
        "krile") echo "krile" ;;
        "nixos") echo "nixos" ;;
        "ICFGG241C3Y03") echo "ICFGG241C3Y03" ;;
        "ICFGG241C3Y03-2") echo "ICFC9DWH494TM-2" ;;
        *) echo "nixos" ;;  # Default to nixos for unknown hosts
      esac
  HOST: '{{.HOST | default .DETECTED_HOST}}'
  # Detect if we're on macOS or Linux
  IS_DARWIN:
    sh: '[[ "$(uname)" == "Darwin" ]] && echo "true" || echo "false"'
  IN_DEVCONTAINER:
    sh: '[[ -n "${INSIDE_DEVCONTAINER:-}" ]] && echo "true" || echo "false"'
  DEVCONTAINER_ATTR:
    sh: |
      arch=$(uname -m)
      if [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
        echo "vscode@devcontainer-aarch64"
      else
        echo "vscode@devcontainer"
      fi

tasks:
  # System management - Auto-detect platform
  build:
    desc: Build the system configuration
    cmd: |
      {{if eq .IN_DEVCONTAINER "true"}}
        nix build .#homeConfigurations."{{.DEVCONTAINER_ATTR}}".activationPackage
      {{else if eq .IS_DARWIN "true"}}
        darwin-rebuild build --flake .#{{.HOST}}
      {{else}}
        nixos-rebuild build --flake .#{{.HOST}}
      {{end}}

  switch:
    desc: Build and switch to the system configuration
    cmd: |
      {{if eq .IN_DEVCONTAINER "true"}}
        nix run .#home-manager -- switch --flake .#"{{.DEVCONTAINER_ATTR}}" -b bak-devcontainer
      {{else if eq .IS_DARWIN "true"}}
        sudo darwin-rebuild switch --flake .#{{.HOST}}
      {{else}}
        sudo nixos-rebuild switch --flake .#{{.HOST}}
      {{end}}

  # Darwin-specific tasks
  darwin-build:
    desc: Build the nix-darwin configuration
    cmd: darwin-rebuild build --flake .#{{.HOST}}
    preconditions:
      - sh: '[[ "$(uname)" == "Darwin" ]]'
        msg: 'This task can only be run on macOS'

  darwin-switch:
    desc: Build and switch to the nix-darwin configuration
    cmd: sudo darwin-rebuild switch --flake .#{{.HOST}}
    preconditions:
      - sh: '[[ "$(uname)" == "Darwin" ]]'
        msg: 'This task can only be run on macOS'

  # NixOS-specific tasks (kept for Linux systems)
  nixos-build:
    desc: Build the NixOS configuration
    cmd: nixos-rebuild build --flake .#{{.HOST}}
    preconditions:
      - sh: '[[ "$(uname)" == "Linux" ]]'
        msg: 'This task can only be run on Linux'
      - sh: '[[ -z "${INSIDE_DEVCONTAINER:-}" ]]'
        msg: 'This task is unavailable inside the devcontainer'

  nixos-switch:
    desc: Build and switch to the NixOS configuration
    cmd: sudo nixos-rebuild switch --flake .#{{.HOST}}
    preconditions:
      - sh: '[[ "$(uname)" == "Linux" ]]'
        msg: 'This task can only be run on Linux'
      - sh: '[[ -z "${INSIDE_DEVCONTAINER:-}" ]]'
        msg: 'This task is unavailable inside the devcontainer'

  boot:
    desc: Build and boot the NixOS configuration (for testing)
    cmd: sudo nixos-rebuild boot --flake .#{{.HOST}}
    preconditions:
      - sh: '[[ "$(uname)" == "Linux" ]]'
        msg: 'This task can only be run on Linux'
      - sh: '[[ -z "${INSIDE_DEVCONTAINER:-}" ]]'
        msg: 'This task is unavailable inside the devcontainer'

  test:
    desc: Test the NixOS configuration
    cmd: nixos-rebuild test --flake .#{{.HOST}}
    preconditions:
      - sh: '[[ "$(uname)" == "Linux" ]]'
        msg: 'This task can only be run on Linux'
      - sh: '[[ -z "${INSIDE_DEVCONTAINER:-}" ]]'
        msg: 'This task is unavailable inside the devcontainer'

  dry-build:
    desc: Perform a dry build to check for errors without applying changes
    cmd: |
      {{if eq .IN_DEVCONTAINER "true"}}
        nix build .#homeConfigurations."{{.DEVCONTAINER_ATTR}}".activationPackage --dry-run
      {{else if eq .IS_DARWIN "true"}}
        darwin-rebuild build --dry-run --flake .#{{.HOST}}
      {{else}}
        nixos-rebuild dry-build --flake .#{{.HOST}}
      {{end}}

  # Home Manager
  home-build:
    desc: Build home-manager configuration
    cmd: |
      {{if eq .IN_DEVCONTAINER "true"}}
        nix build .#homeConfigurations."{{.DEVCONTAINER_ATTR}}".activationPackage
      {{else}}
        home-manager build --flake .#jhettenh@{{.HOST}}
      {{end}}

  home-switch:
    desc: Switch home-manager configuration
    cmd: |
      {{if eq .IN_DEVCONTAINER "true"}}
        nix run .#home-manager -- switch --flake .#"{{.DEVCONTAINER_ATTR}}" -b bak-devcontainer
      {{else}}
        home-manager switch --flake .#jhettenh@{{.HOST}}
      {{end}}

  # Maintenance
  update:
    desc: Update flake inputs
    cmd: nix flake update

  gc:
    desc: Garbage collect old generations
    cmd: |
      nix-collect-garbage -d
      {{if ne .IN_DEVCONTAINER "true"}}
        sudo nix-collect-garbage -d
      {{end}}

  optimize:
    desc: Optimize nix store
    cmd: nix-store --optimise

  # Development
  check:
    desc: Check flake for errors
    cmd: nix flake check

  fmt:
    desc: Format nix files
    cmd: nixpkgs-fmt .

  repl:
    desc: Start nix repl with flake
    cmd: nix repl --expr 'builtins.getFlake "."'

  # Host-specific tasks
  krile:
    desc: Switch to krile configuration
    cmd: task switch HOST=krile

  nixos:
    desc: Switch to nixos configuration
    cmd: task switch HOST=nixos

  # Service management
  service-status:
    desc: Check status of rclone services
    cmd: systemctl --user status rclone-*
    preconditions:
      - sh: '[[ -z "${INSIDE_DEVCONTAINER:-}" ]]'
        msg: 'User systemd is unavailable inside the devcontainer'

  logs:
    desc: Show logs for a specific service
    cmd: journalctl -u {{.SERVICE}} -f
    preconditions:
      - sh: '[[ -z "${INSIDE_DEVCONTAINER:-}" ]]'
        msg: 'journald is unavailable inside the devcontainer'

  # Quick actions
  edit:
    desc: Open the NixOS configuration in VS Code
    cmd: code ~/.config/nix

  upgrade:
    desc: Update nixpkgs and rebuild the system
    cmd: |
      nix flake update
      {{if eq .IN_DEVCONTAINER "true"}}
        nix run .#home-manager -- switch --flake .#"{{.DEVCONTAINER_ATTR}}" -b bak-devcontainer
      {{else if eq .IS_DARWIN "true"}}
        sudo darwin-rebuild switch --flake .#{{.HOST}}
      {{else}}
        sudo nixos-rebuild switch --flake .#{{.HOST}}
      {{end}}
