system: "base24"
name: "Monokai Spectrumish"
author: "Jeremy Hettenhouser"
variant: "dark"
palette:
  base00: "#222222"
  base01: "#363537"
  base02: "#525053"
  base03: "#69676c"
  base04: "#8b888f"
  base05: "#bab6c0"
  base07: "#f7f1ff"
  base06: "#fbf8ff"
  base08: "#FC618D"
  base09: "#fd9353"
  base0A: "#FCE566"
  base0B: "#7BD88F"
  base0C: "#5AD4E6"
  base0D: "#948ae3"
  base0E: "#fc618d"
  base0F: "#fef20a"
  base10: "#191919"
  base11: "#222222"
  base12: "#FC618D"
  base13: "#FCE566"
  base14: "#7BD88F"
  base15: "#5AD4E6"
  base16: "#948AE3"
  base17: "#FD9353"
