// Package cmd wires the gopwgen command tree and configuration loading.
//
// The package owns the CLI integration layer: Cobra commands, Viper-backed
// configuration, and the starter config generated by init-config.
package cmd
