package appconfig

import (
	"strings"
	"testing"
)

func TestRenderIncludesExpectedSections(t *testing.T) {
	text := Render(Default(), "gopwgen")

	mustContain := []string{
		"# Generated by gopwgen init-config.",
		"[password]",
		"word_count = 5",
		"max_word_length = 12",
		"separator = \"-\"",
		"case_format = \"traincase\"",
		"append_requirements = true",
	}

	for _, expected := range mustContain {
		if !strings.Contains(text, expected) {
			t.Fatalf("rendered config missing %q", expected)
		}
	}
}
