package appconfig

import (
	"fmt"
	"strings"
)

type Config struct {
	Password PasswordConfig `mapstructure:"password"`
}

type PasswordConfig struct {
	WordCount          int    `mapstructure:"word_count"`
	MaxWordLength      int    `mapstructure:"max_word_length"`
	Separator          string `mapstructure:"separator"`
	CaseFormat         string `mapstructure:"case_format"`
	AppendRequirements bool   `mapstructure:"append_requirements"`
	RequireUppercase   bool   `mapstructure:"require_uppercase"`
	RequireLowercase   bool   `mapstructure:"require_lowercase"`
	RequireNumbers     bool   `mapstructure:"require_numbers"`
	RequireSpecial     bool   `mapstructure:"require_special"`
	WordgenDataset     string `mapstructure:"wordgen_dataset"`
}

func Default() Config {
	return Config{
		Password: PasswordConfig{
			WordCount:          5,
			MaxWordLength:      12,
			Separator:          "-",
			CaseFormat:         "traincase",
			AppendRequirements: true,
			RequireUppercase:   true,
			RequireLowercase:   true,
			RequireNumbers:     true,
			RequireSpecial:     true,
			WordgenDataset:     "embedded://all.json.zst",
		},
	}
}

func Render(config Config, binaryName string) string {
	var builder strings.Builder

	fmt.Fprintf(&builder, "# Generated by %s init-config.\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Generate a password with:\n")
	fmt.Fprintf(&builder, "#   %s password\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Override password settings with environment variables like:\n")
	builder.WriteString("#   GOPWGEN_PASSWORD_WORD_COUNT=6\n")
	builder.WriteString("#   GOPWGEN_PASSWORD_SEPARATOR=\"_\"\n")
	builder.WriteString("#   GOPWGEN_PASSWORD_CASE_FORMAT=\"camelcase\"\n")
	builder.WriteString("#\n")
	builder.WriteString("# Password configuration produces: Harbor-Lantern-Maple-Canvas-Breeze7!\n")
	builder.WriteString("# where Word is from wordgen and extra characters meet common password requirements.\n\n")

	builder.WriteString("[password]\n")
	fmt.Fprintf(&builder, "word_count = %d\n", config.Password.WordCount)
	fmt.Fprintf(&builder, "max_word_length = %d\n", config.Password.MaxWordLength)
	fmt.Fprintf(&builder, "separator = %q\n", config.Password.Separator)
	fmt.Fprintf(&builder, "case_format = %q\n", config.Password.CaseFormat)
	fmt.Fprintf(&builder, "append_requirements = %t\n", config.Password.AppendRequirements)
	fmt.Fprintf(&builder, "require_uppercase = %t\n", config.Password.RequireUppercase)
	fmt.Fprintf(&builder, "require_lowercase = %t\n", config.Password.RequireLowercase)
	fmt.Fprintf(&builder, "require_numbers = %t\n", config.Password.RequireNumbers)
	fmt.Fprintf(&builder, "require_special = %t\n", config.Password.RequireSpecial)
	fmt.Fprintf(&builder, "wordgen_dataset = %q\n\n", config.Password.WordgenDataset)

	return builder.String()
}
