system: "base16"
name: "monokai"
author: "Jeremy Hettenhouser"
variant: "dark"
palette:
  base00: "#131313"
  base01: "#191919"
  base02: "#222222"
  base03: "#363537"
  base04: "#525053"
  base05: "#69676c"
  base06: "#8b888f"
  base07: "#bab6c0"
  base08: "#f7f1ff"
  base09: "#fc618d"
  base0A: "#fd9353"
  base0B: "#7bd88f"
  base0C: "#5ad4e6"
  base0D: "#948ae3"
