{
	"data": "ENC[AES256_GCM,data:HYIr2tOH11/QNfsHHkCWpBimJUfd3qmT4HWL79CHjS8lpqh/pHlLSe7C5r/6TJ3BjfrYYZMfzPu2JnDuQWu1QXUJ3R4qQqfqaicgwG4niRSCv2NB84gCTaRqMZdH6tnoIPOuP/SSoTcNG08zewlIjv+mZaFtYtOl7xmMOZNMJGdHtpjDqYzg+UntU+NVt3xY0+DUWK9pcQxtFMr6RiB9uC4JWn7UK64BiA7nDZWNIvRYmHPVqhBaXEgrTVXt7AEnCY4wlCrknnufT459EfHI7UqRFlWjCp3ouyynEBDKpOo2/Hr5aK2BO4+46hdmONuSVtBItE0jHjhIHA47M7NuIZ47sRW/iVL5JBgztsyvKLCIuQtB4NPdzhBLEu3Pv0jAWZgZ3bj27tVeRF1p+4oqHh1x1wJi/cMgrvg5v4jKnNtlqxBF/3cKJSCpKED/co88xUUbI8BJU+tPECuoDU6Jmf6uszLxCcIlhXWnO3xS7ki4WpITQ538jbbu6zSuneIq52ffkc0zNDbzfMxeizJTw7WEk8Z3xj8=,iv:QTXiOlDqb81g3js3wfwsVTPd5iTKO8DdVlva/zNj8FA=,tag:Cqza2amM8tHV6LA5YAkUYg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19vlys87e2zs36pv4aq2m026qrxxk4e0wh44gxr3y98shrpnamvsqm7mgpk",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMXRxb2RBUTF2UXJ6QjJo\nNzkxUTJGQkpUVTd5NGY1UWNJVTNCYzZRQlgwCjdmYmkrWnNLMUU3RGVJM0Y0VXd5\nTDFkcU9oQ1U3MCtBeDlrTUcwMUNoVEkKLS0tIFlxdkJBWlR3T0Y1ZmhmQXVOaGlG\nWWg2OVNOWGh6ekVvNFltdzRkVnZsMTAKYAUYb9i5r2M4MPBtDzf50WBzozD3GDUP\nHepmlLcUgeJLcvBYV6m5icHv1l47T4wvnRaEFUFfckUh4Fggtx4Jaw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-27T16:43:56Z",
		"mac": "ENC[AES256_GCM,data:eNz4+UQrJYoVLe1GVfcZRYBZBjL0Lj3zTBLPjVwxw8BcAPKMN+1MX4V8soKGqo7oBIM2fxqzpXKxD0fNEtvbiNHZ7UPfbt+SnDiBMY3dAsM0DJk70NQv5MWFdlRxNjcu0SRxxk2Jj5aWVcLNvihPRsqeg68q0/5DNhldsfCWdy8=,iv:i/vVP3w73zW1OyNnhrB1vpvZuVRn2QnUgyk+5KF+DPk=,tag:S6dUrAyQlBl29+ymEr/g5Q==,type:str]",
		"version": "3.12.1"
	}
}
