{
	"data": "ENC[AES256_GCM,data:F//0Jt/FpdGqyIi8ZNDj/eMn0qOR9lDTUaAhJ+vqAErb5zO+tX/qqkBSluj9p2O3rgagaWiwRz+5FwQ7jFq1HLPmxej7x+bXqoYNN0DlYhyyv2hh5+l8N+7oN4+nBDC9K6WOO0bmdgG5vSk4l8Z00j9kdY2FWL341g3ykuC47at+czTXc+nA2f78lSrw/XAjG6VyGy4vJkaTAhSc3PgnA3byUJWAkDaqKxN//jCPU33MiJAAGgUhL0GxT1FCyS1hXC5vSJ+pHbOaIkrpqjgFo35LIEA8N3b5ll6mbaciS4Ns+tw/cC4D4MlZznza4r0U/UC1636hmqbYrCS9XmKjI1sqRE/rCgfVGtLGS7E1ktGD31kh8XzGAAomTI9QbPc2nS/c96KaLAewEp5YIBrEwBCwktPKw1rL8GbzWD+Bh0GocButzFX6SSHPHhRfsEg1OF303y9Jo9oEviAZjlVem48CDKMI8NoLc+aRIMDNZjkH9829s/k0ZlPGwkAU3eqmcol+vDIplcK0ZhlafcC8RT5Buw2sjSXvz0W7xHKtSO16dXy1o/dn49Ne/YJBxoZ/GqiW,iv:2u+CLz06bY8Qq7WFkUZ/88OcEd3xAVH4qDMZpx7Tq/M=,tag:EHHKRAMbPfEbd17aE3UdPQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYllFTDJ1VWd1RGRDN2M3\nUVRQNjloaDdDU1o3N2l0cEdNbmpqZ3YrYW13CkpmYnFsV0tEa0NITkJra2MvYTdh\ndGlRZFF4bEJsb3YzcVQyMTZwa0dtOEkKLS0tICtpY0FPcDBESXpvZkpxQWJqVVdM\nMzF2cEszYllQaktPQnpxTWZySnczbkUKu0v3wJ2KmaWi2u8wMB7OwGvUHiVFuavM\nFDt9iHDCUUB5DwwDtujPYyhDoTCAc7Feviw+gf2eMJgeJ8azxGnSJA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age19vlys87e2zs36pv4aq2m026qrxxk4e0wh44gxr3y98shrpnamvsqm7mgpk"
			}
		],
		"lastmodified": "2026-08-25T20:06:35Z",
		"mac": "ENC[AES256_GCM,data:KgueK7ePWx3cv35RInY2gPvfgvcd9ZJ7TDt9b+SN3c9LzHKQ0TXbNgp39aB966gEB9Sza4ITUG0iTtkq5eDnxm9QDGMP+cvb302CtfhTMe38SIZEOcbdh269c/a4mKLn/s2zs0+hSUniPalzHFJ7tP1qs76+wAtdKK91lweuK9Y=,iv:JQN63kp4PhiZLiCQLr/dZaF6s/pKgtEGZBYdwz7RmOc=,tag:rq4TfMGQvgsR+ZZ7DfH1yw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.3"
	}
}
