{
	"data": "ENC[AES256_GCM,data:FRjMS4ZQj4XYd6o1h5MSqHUwv8iDIjGgdIwjGxAd59fO7a8wxD63mG65Wqb+ppAq9DiJN4ibynU80eC1qVM4PaiR8Jgp6gflkZ4WQCaxMbgChmjmcvT9DYvHjgbqvQGVHoO4oBZZzYqxoicvOLBGbH9bmT3rQaP4OqKQUTBwI5jNpEV7pGhyF6o/6MtZUJ+jPBbGoIAUwPRcEPgYr3h/em6vc1eTy7iqfeIGatyIh+mM63LkW9CKW3fgIqiPKF60EkSQC0PxDtCpkOUifhsKnR9dxDjgdA/vOTTtRQQotHaRRlaVQRN0Jl/+AXWwMp2HNjVvae1TMVmvlHP3S395leD8kstFVGxMhdv433uvX4iM5a+qjy1ijSFwPMDH8d5c5hAQoG1jtj6alsVQvTCeWVtSA4NUygmTalget5E37+w/0uoKbk/1njY+r0OCKt+jzzk7b2YCQhIb2DoNl6wqi85RB8a0tetdETEImwOrENWLwh1DAEYHY55AaGQiddMX0GpC7Q3OAQ6NfjlPLZnGe5ODLvahD88maYDFw+3cN709YezsdKGT5QLA0IKYbNS5k1zu,iv:erDxbpf04DItq2eKomclxgQ5yQ7B/fqymtfEg5tQ1n4=,tag:ZHm/2XIKwdnKsICpJWX4+g==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19vlys87e2zs36pv4aq2m026qrxxk4e0wh44gxr3y98shrpnamvsqm7mgpk",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYllFTDJ1VWd1RGRDN2M3\nUVRQNjloaDdDU1o3N2l0cEdNbmpqZ3YrYW13CkpmYnFsV0tEa0NITkJra2MvYTdh\ndGlRZFF4bEJsb3YzcVQyMTZwa0dtOEkKLS0tICtpY0FPcDBESXpvZkpxQWJqVVdM\nMzF2cEszYllQaktPQnpxTWZySnczbkUKu0v3wJ2KmaWi2u8wMB7OwGvUHiVFuavM\nFDt9iHDCUUB5DwwDtujPYyhDoTCAc7Feviw+gf2eMJgeJ8azxGnSJA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-27T16:43:56Z",
		"mac": "ENC[AES256_GCM,data:4EDUAuKPvxjh9QDutRwhvYwC0mkmOtnePH1NO3scGsrUlTi0bksdu9fdydzSvvuZYPGeXbbaj1Io+WKd3nD3sjCritzVXw7WISepUYMP7FUw7DXneAF9T/eHDk90XcNOSrwhh5ef9uNYar78nIa44I+3+jLjckex17FuxvD//HI=,iv:L8r2/+GKbEGgZNLUV0fYcpUW0fxGvKv2osH/MXgiCvQ=,tag:GypYtqNPoTRIYJnbZLWguw==,type:str]",
		"version": "3.12.1"
	}
}
