{
	"data": "ENC[AES256_GCM,data:VrmHaXlyULLHb6tXgaKY5ua1sQPgeA+pCVHrBSnPlnUKBu7BSlISucsOYEumvRei1Jwp2bjRf+E3CQcdUPyJjgFjjJuGnIr1hHr0uNzhW+ko8/2s8WZnXm1QANUf9kPEYzIshMiNtKiGYZT/Rm/oeRL5DBSdKWPvIa7u2SfpvreTo7BNLZ/QflKUqWcYox+CXm6yZM33GvqLbJatfbI54+tXG05+qnVylNsSUoFBUlvpmRyC94ORfaN1zO+is4vh/9AeGWu7mGnaAxrOYW5oapzoN5c5aDf65htjUKGJ2PrMUsQX0llrOgnhc64oYhHIwfTocLa1hPHA1PhVQk8VVLwSIHY6eCgw8Yb3LZ7gbo20sEYjNsTj9nxBNqzJWinxQ0YTNo7VIM99FQ6spRyepgMc90TFecAMPoJ2hSusTVdqaEfWGQUimBQLEQyK3eslSU03c6xe9jAzwLoznlJ1JYc4gm0z27HFgMLMvHTH3qwtPF6J1tDf0PQE71PJn60fg1Ut2txzHHW/kDSFdoVbdtJIGeDlpNQqVLcEfP5R4mF1pAs2ZsI+G6B8qUg52/XAamJXcAD5Reosj7FA3ENUZBzfKek8AmHl8sZVlMo=,iv:wGkaw5sJylRC8o4opNhYTfwA6zRd36eWVnVWeIrppoA=,tag:rXYrqGLdowxjf2wOSf76Zg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSkhYUVBIR3pVLzF2NGhz\nMkpJbkxyUktLQlY1dzZxTnpBUURNaGNDVTFzCkt3bEczMzQvZ25qSGpnMGx6TXNU\nNHhPcEtCRzA0UWhmOFJ0UzB3a2MwMkEKLS0tIFEzOXViWFpTOWgwczN6OWhRNVZv\nYlcyRGJjbE5Rc0ZiUkJrSUxJNWxISEUKRc7Ha6KIUkB/VihblMFJbVgCRNbRSD54\nzLawqbO6bh7Vn4onmWsLXuUMuFYsYeoNrxUhZjmae4JPGRUXwH7xrg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age19vlys87e2zs36pv4aq2m026qrxxk4e0wh44gxr3y98shrpnamvsqm7mgpk"
			}
		],
		"lastmodified": "2026-08-28T22:36:57Z",
		"mac": "ENC[AES256_GCM,data:fvITAP8iykyo3i9QKPPuaJX8KdvYbW58XT0usfqSGWMvMr92EJrJJPJHC1NIT4ATTX5DRic5Ia4gvK5CWKNt5xasvA6t9rt7Xy3zMBTrQR0HexPpa4OUSuk9NHO0Td76bA8HT80iYjMdwN9uhOoc7pOwBsv7+F7njs4PWKKLFOA=,iv:mW3exAFcD3uvzc9jim1fR3DkHR9JsrNrO1u9ENhx6Xk=,tag:qTZSQR+qlxfNj7AxYgOvuQ==,type:str]",
		"version": "3.13.3"
	}
}
